[workspace]
members = [
  "crates/authz-cedar",
  "crates/http-server",
  "crates/jmap-tmp",
  "crates/data",
  "crates/schema-manager",
  "crates/schema-provider",
]
resolver = "2"

[workspace.lints.rust]
warnings = 'deny' # Treat all warnings as errors
# Inherited from Wasmtime
trivial_numeric_casts = 'warn'
unstable_features = 'warn'
unused-lifetimes = 'warn'
unused-macro-rules = 'warn'
unused_extern_crates = 'warn'
unused_import_braces = 'warn'

[workspace.lints.clippy]
expect_used = 'deny'
indexing_slicing = 'deny'
panic = 'deny'
unwrap_used = 'deny'

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
fiber-authz-cedar = {path = "crates/authz-cedar"}
cedar-policy = "4"
hyper = {version = "1.6.0", default-features = false}
itertools = "0.14"
murmur3 = "0.5"
rustls = {version = "0.23", default-features = false, features = ["std", "tls12"]}
rustls-pemfile = {version = "2.2", default-features = false, features = ["std"]}
serde = {version = "1", default-features = false}
serde_cbor = "0"
serde_json = {version = "1", default-features = false}
sqlparser = "0.53"
sqlx = {version = "0.8", features = ["postgres", "runtime-tokio-rustls", "macros"]}
thiserror = "2"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
tokio-rustls = {version = "0.26", default-features = false}
tracing = "0.1"
wash-runtime = {git = "https://github.com/wasmcloud/wash.git", branch = "main"}
wasmtime = {version = "40", default-features = false}
wasmtime-wasi-http = {version = "38", default-features = false}
wstd = {version = "0.6"}
