[package]
edition = "2024"
name = "fiber-authz-cedar"
version = "0.1.0-draft"

[badges.maintenance]
status = "actively-developed"

[dependencies]
anyhow = {workspace = true}
async-trait = {workspace = true}
cedar-policy = {workspace = true}
tokio = {workspace = true}
tracing = {workspace = true}
wash-runtime = {workspace = true}
wasmtime = {workspace = true}
