[package]
edition = "2024"
name = "fiber-data"
version = "0.1.0-draft"

[badges.maintenance]
status = "actively-developed"

[dependencies]
async-trait = {workspace = true}
tokio = {workspace = true, features = ["sync", "net", "macros"]}
wash-runtime = {workspace = true}
wasmtime = {workspace = true, features = ["component-model", "cranelift", "pooling-allocator"]}
anyhow = {workspace = true}
tracing = {workspace = true}
